### ISSUE TITLE
Installing the library directly via git fails

### ISSUE THREAD

**Issue by audunth** [audunth/uit_scripts#4]
Several of us have had some trouble installing the library. Obviously, cloning the repo and adding it to the path works fine.
However, installing seems to fail:

### Installing directly from git does not work:

1. Created new conda environment with pip and git:
`conda create --name testing git pip numpy mpmath scipy`
`conda activate testing`
 
2. Installed directly from git without issues:
`pip install git+git://github.com/audunth/uit_scripts@master`

3. Import fails:
`python`
<pre>
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import uit_scripts
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'uit_scripts'
</pre>

### Neither does cloning the repo and installing with setup

2. Clone the repo:
`cd opt/anaconda3/envs/testing`
`mkdir repos`
`cd repos`
`git clone https://github.com/audunth/uit_scripts.git`

3. Install
`cd uit_scripts`
`python setup.py install`
<pre>
running install
running bdist_egg
running egg_info
creating uit_scripts.egg-info
writing uit_scripts.egg-info/PKG-INFO
writing dependency_links to uit_scripts.egg-info/dependency_links.txt
writing top-level names to uit_scripts.egg-info/top_level.txt
writing manifest file 'uit_scripts.egg-info/SOURCES.txt'
package init file 'uit_scripts/__init__.py' not found (or not a regular file)
reading manifest file 'uit_scripts.egg-info/SOURCES.txt'
writing manifest file 'uit_scripts.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.macosx-10.9-x86_64
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying uit_scripts.egg-info/PKG-INFO -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying uit_scripts.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying uit_scripts.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying uit_scripts.egg-info/not-zip-safe -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
copying uit_scripts.egg-info/top_level.txt -> build/bdist.macosx-10.9-x86_64/egg/EGG-INFO
creating dist
creating 'dist/uit_scripts-1.0-py3.8.egg' and adding 'build/bdist.macosx-10.9-x86_64/egg' to it
removing 'build/bdist.macosx-10.9-x86_64/egg' (and everything under it)
Processing uit_scripts-1.0-py3.8.egg
creating /Users/ath019/opt/anaconda3/envs/testing/lib/python3.8/site-packages/uit_scripts-1.0-py3.8.egg
Extracting uit_scripts-1.0-py3.8.egg to /Users/ath019/opt/anaconda3/envs/testing/lib/python3.8/site-packages
Adding uit-scripts 1.0 to easy-install.pth file

Installed /Users/ath019/opt/anaconda3/envs/testing/lib/python3.8/site-packages/uit_scripts-1.0-py3.8.egg
Processing dependencies for uit-scripts==1.0
Finished processing dependencies for uit-scripts==1.0
</pre>

4. Test:
`cd ~`
`python`
<pre>
Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from uit_scripts.shotnoise import gen_shot_noise as gsn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'uit_scripts'
>>> 
</pre>

**Comment by audunth** [comment]
In step 3 during install from cloned repo in my previous comment, the installer throws a warning:
<pre>
warning: install_lib: 'build/lib' does not exist -- no Python modules to install
</pre>

There appears to be an issue with a missing file?
<pre>
(testing) ath019@tek-ift-m0009 uit_scripts % python setup.py build
running build
running build_py
package init file 'uit_scripts/__init__.py' not found (or not a regular file)
</pre>

**Comment by makorzen** [comment]
> In step 3 during install from cloned repo in my previous comment, the installer throws a warning:
> 
> warning: install_lib: 'build/lib' does not exist -- no Python modules to install
> There appears to be an issue with a missing file?
> 
> (testing) ath019@tek-ift-m0009 uit_scripts % python setup.py build
> running build
> running build_py
> package init file 'uit_scripts/__init__.py' not found (or not a regular file)

Yes, in order to install with ```python setup.py install``` one needs to add an empty ```uit_scripts/__init__.py``` file, and modify ```setup.py``` to find packages automatically, like so:
```
@@ -1,5 +1,5 @@
 import os
-from setuptools import setup
+from setuptools import setup, find_packages
 
 name = 'uit_scripts'
 
@@ -17,7 +17,7 @@ setup(name=name,
       author_email='audun.theodorsen@uit.no',
       license='GPL',
       version='1.0',
-      packages=['uit_scripts'],
+      packages=find_packages(),
       classifiers=[
         'Intended Audience :: Education',
         'Intended Audience :: Science/Research',
```

with those changes the instataltion with 
```python setup.py build``` 
```python setup.py install``` 
worked for me at least. 
UPDATE:
Note, I am not using ```conda``` (at all) nor ```pip``` for this installation. ```uit_scripts``` get installed globaly using ```python``` command like this.

**Comment by Sosnowsky** [comment]
I have successfully installed it with 
`pip install -e git+git://github.com/audunth/uit_scripts#egg=uit_scripts`

Also, installing by cloning the repo also worked for me after adding -e flag, i.e. somthing like
`pip install -e ../uit_scripts/`

**Comment by audunth** [comment]
Thank you both. I can get @Sosnowsky's solution to work, but not @makorzen's.

**Comment by gregordecristoforo** [comment]
As a general remark, I would be careful installing packages via `python setup.py install` since this might interfere with the python libraries used by your system.

I added a short installation guide in the README of the `next` branch in order to reduce the confusion.
