### ISSUE TITLE
Add requirements

### ISSUE THREAD

**Issue by audunth** [audunth/uit_scripts#5]
The library depends on numpy, mpmath and scipy. It is possible to list these as requirements?

**Comment by gregordecristoforo** [comment]
I added the requirements to the setup.py in the next branch so you can test it.

For now I set the versions to:
 'numpy>=1.15.0',
 'scipy>=1.4.0',
 'mpmath>=1.0.0'

and 

python_requires='>=3.0'

I have not tested the scripts for older python versions but that can be done if required.

**Comment by audunth** [comment]
Thank you. No, I don't think we should worry about backwards compatibility.
